name: Wheel Windows amd64

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows_amd64:
    uses: ./.github/workflows/_wheel-build.yml
    permissions:
      id-token: write
    with:
      artifact_name: wheel-windows-amd64
      runs_on: windows-latest
      cibw_archs: AMD64
      publish: false
    secrets: inherit
